// <auto-generated />
using System;
using ApiTesting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTesting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915175714_AddUserAndAuthToken")]
    partial class AddUserAndAuthToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ApiTesting.Models.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("ApiTesting.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "zVX425OzpyPcasd3oSsCCA==:FjWNWFf7HhMaucTg5sK3rV56qw9udvVeqvKPM4tssyA=",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ApiTesting.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HumidityPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("PrecipitationChancePercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindDirectionDegrees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindSpeedKmh")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 9, 16),
                            HumidityPercent = 60,
                            Latitude = 59.913899999999998,
                            Location = "Oslo",
                            Longitude = 10.7522,
                            PrecipitationChancePercent = 20,
                            Summary = "Mild",
                            TemperatureC = 20,
                            WindDirectionDegrees = 270,
                            WindSpeedKmh = 12
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 9, 17),
                            HumidityPercent = 55,
                            Latitude = 48.8566,
                            Location = "Paris",
                            Longitude = 2.3521999999999998,
                            PrecipitationChancePercent = 10,
                            Summary = "Warm",
                            TemperatureC = 23,
                            WindDirectionDegrees = 180,
                            WindSpeedKmh = 8
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 9, 18),
                            HumidityPercent = 70,
                            Latitude = 52.520000000000003,
                            Location = "Berlin",
                            Longitude = 13.404999999999999,
                            PrecipitationChancePercent = 40,
                            Summary = "Cool",
                            TemperatureC = 15,
                            WindDirectionDegrees = 45,
                            WindSpeedKmh = 18
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 9, 19),
                            HumidityPercent = 80,
                            Latitude = 40.416800000000002,
                            Location = "Madrid",
                            Longitude = -3.7038000000000002,
                            PrecipitationChancePercent = 60,
                            Summary = "Chilly",
                            TemperatureC = 5,
                            WindDirectionDegrees = 315,
                            WindSpeedKmh = 25
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 9, 20),
                            HumidityPercent = 35,
                            Latitude = 41.902799999999999,
                            Location = "Rome",
                            Longitude = 12.4964,
                            PrecipitationChancePercent = 5,
                            Summary = "Hot",
                            TemperatureC = 30,
                            WindDirectionDegrees = 90,
                            WindSpeedKmh = 5
                        });
                });

            modelBuilder.Entity("ApiTesting.Models.AuthToken", b =>
                {
                    b.HasOne("ApiTesting.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
